environments:
  - name: "ds-env-py312-ml"
    python: "3.12"
    conda_packages:
      - numpy=1.26
      - scipy=1.13
    uv_packages:
      - scikit-learn==1.5.0
      - pandas==2.2.3
      - seaborn==0.13.2
      - transformers==4.37.0
      - pillow==10.2.0
      - nltk==3.8.1
      - requests==2.31.0

  - name: "ds-env-py312"
    python: "3.12"
    conda_packages:
      - numpy=1.26
      - scipy=1.13
    uv_packages:
      - scikit-learn==1.4.2
      - pandas==2.2.3
      - seaborn==0.13.2

  - name: "ds-env-py311"
    python: "3.11"
    conda_packages:
      - numpy=1.25
      - scipy=1.11
    uv_packages:
      - scikit-learn==1.2.2
      - pandas==1.5.3
      - seaborn==0.12.2

  - name: "ds-env-py310"
    python: "3.10"
    conda_packages:
      - numpy=1.23
      - scipy=1.9
    uv_packages:
      - scikit-learn==1.0.2
      - pandas==1.3.5
      - seaborn==0.11.2
